title: Christopher Vallone
theme: minima
minima:
  skin: dark
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      css: "assets/css/style.css"
include:
  - _includes/head-custom.html
